### ISSUE TITLE
Review all attributes with focus on required/mutable flags

### ISSUE THREAD

**Issue by arax** [EGI-FCTF/rOCCI-core#33]
(...)

**Comment by valtri** [comment]
Also **occi.storagelink.deviceid** and **occi.storage.state** (https://github.com/jeanparpaillon/pOCCI/commit/3deffd3eb76d52fd3999029276e7e0c49995ec24, https://github.com/jeanparpaillon/pOCCI/commit/d4329687e5d5dc858a442710efc03126b73e8855).

**Comment by arax** [comment]
@valtri 
What's the problem with `deviceid` and `state`?

**Comment by valtri** [comment]
They are not marked as required. But it is probably not a problem in rOCCI-server implementation, right?

They are just mentioned as required in OCCI standard and erlang implementation requires them (https://github.com/erocci/erocci_core)? Just adding example values to pOCCI testsuite may be proper solution.

**Comment by arax** [comment]
Well ... `deviceid` cannot be required, not in real-world implementations. And `state` is usually provided by the server, not by the client ... and is immutable for the client.
